DROP TABLE IF EXISTS phones;
CREATE TABLE phones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY primary key,
    country_code VARCHAR NOT NULL ,
    number VARCHAR NOT NULL ,
    is_active BOOLEAN
);